apiVersion: apps/v1
kind: Deployment
metadata:
  name:  myapp-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app:  myapp
    spec:
      containers:
      - name:  myapp-container
        image:  nginx
      affinity:
        nodeAffinity:
          # preferredDuringSchedulingIgnoredDuringExecution:
          # - preference:
          #     matchExpressions:
          #     - key: size
          #       operator: In
          #       values: 
          #       - small
          #   weight: 1
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: size
                operator: In
                values:
                - small