apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
      
  volumes:
  - name: test
    emptyDir: {}


