apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: myapp-daemon
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: nginx