apiVersion: v1
kind: Pod
metadata:
  name: "myapp"
  labels:
    app: "myapp"
    env: dev
spec:
  containers:
  - name: myapp
    image: nginx
    env:
      - name: DB_HOST
        value: 192.168.0.0
      - name: DB_USER
        value: admin
      - name: DB_PASS
        value: secret
    