apiVersion: v1
kind: Pod
metadata:
  name: "myapp"
  labels:
    app: "myapp"
    env: dev
spec:
  initContainers:
  - name: init-container1
    image: busybox:1.28
    args: ["sleep1", "30"]
  - name: init-container2
    image: busybox:1.28
    args: ["sleep", "30"]
  containers:
  - name: container
    image: nginx
