apiVersion: v1
kind: Pod
metadata:
  name: "myapp"
  labels:
    app: "myapp"
    env: dev
spec:
  containers:
  - name: container1
    image: nginx
  - name: container2
    image: busybox
    args: ["sleep","300"]
