apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - myapp1
          - myapp2
      - key: tier
        operator: NotIn
        values:
          - backend
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp1
    spec:
      containers:
      - name: nginx-container
        image: nginx